from panda3d.core import Point3
from .SpecImports import *
LobbyParent = 10014
BoilerParent = 10030
PipeLeftParent = 10023
PipeRightParent = 10032
OilParent = 10034
ControlParent = 10037
DuctParent = 10036
CenterSiloBattleCellParent = 10064
CenterSiloParent = 20095
SigRoomParent = 20058
WestSiloParent = 20094
WestSiloBattleCellParent = 10047
EastSiloParent = 20096
EastSiloBattleCellParent = 10068
Fatalfact1leftParent = 11000
Fatalfact1RightParent = 11001
FatalFact2BattleRoomParent = 11009
FatalFact3BattleRoomParent = 11018
LobbyCell = 0
BoilerCell = 1
PipeLeftCell = 2
PipeRightCell = 3
OilCell = 4
ControlCell = 5
DuctCell = 6
CenterSiloCell = 7
SigRoomCell = 8
WestSiloCell = 9
EastSiloCell = 10
FF1LeftCell = 11
FF1RightCell = 12
FF2BatRCell = 13
FF3BatRCell = 14
BattleCells = {LobbyCell: {'parentEntId': LobbyParent,
             'pos': Point3(0, 0, 0)},
 BoilerCell: {'parentEntId': BoilerParent,
              'pos': Point3(0, 0, 0)},
 OilCell: {'parentEntId': OilParent,
           'pos': Point3(0, 0, 0)},       
 ControlCell: {'parentEntId': ControlParent,
               'pos': Point3(0, 0, 0)},
 CenterSiloCell: {'parentEntId': CenterSiloBattleCellParent,
                  'pos': Point3(0, 0, 0)},
 PipeLeftCell: {'parentEntId': PipeLeftParent,
                'pos': Point3(0, 0, 0)},
 PipeRightCell: {'parentEntId': PipeRightParent,
                 'pos': Point3(0, 0, 0)},
 DuctCell: {'parentEntId': DuctParent,
            'pos': Point3(0, 0, 0)},
 SigRoomCell: {'parentEntId': SigRoomParent,
               'pos': Point3(0, 0, 0)},
 WestSiloCell: {'parentEntId': WestSiloBattleCellParent,
                'pos': Point3(0, 0, 0)},
 EastSiloCell: {'parentEntId': EastSiloBattleCellParent,
                'pos': Point3(-20, -10, 0)},
 FF1LeftCell: {'parentEntId': Fatalfact1leftParent,
                'pos': Point3(0, 0, 0)},
 FF1RightCell: {'parentEntId': Fatalfact1RightParent,
                 'pos': Point3(0, 0, 0)},
 FF2BatRCell: {'parentEntId': FatalFact2BattleRoomParent,
               'pos': Point3(0, 0, 0)},
 FF3BatRCell: {'parentEntId': FatalFact3BattleRoomParent,
               'pos': Point3(0, 0, 0)}}                
CogData = [{'type': 'm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20078,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20009,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20079,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 9,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 9,
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 10,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 9,
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 9,
  'battleCell': OilCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60134,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 9,
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 9,
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 9,
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 10,
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20075,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 10,
  'battleCell': CenterSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': CenterSiloParent,
  'boss': 1,
  'level': 11,
  'battleCell': CenterSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 10,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': 0},
 {'type': 'm', # mingler or gladhander
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 8,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 10,
  'battleCell': WestSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20097,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 8,
  'battleCell': WestSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20098,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 9,
  'battleCell': WestSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20099,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 10,
  'battleCell': EastSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20100,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 8,
  'battleCell': EastSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20101,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 9,
  'battleCell': EastSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20102,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20109,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20110,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeLeftCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20111,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20106,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20107,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeRightCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20108,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 9,
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 9,
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 9,
  'battleCell': DuctCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20068,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': SigRoomCell,
  'pos': Point3(5, 3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 10,
  'battleCell': SigRoomCell,
  'pos': Point3(5, 10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': Fatalfact1leftParent,
  'boss': 0,
  'level': 11,
  'battleCell': FF1LeftCell,
  'pos': Point3(-3, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11003,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': Fatalfact1leftParent,
  'boss': 0,
  'level': 9,
  'battleCell': FF1LeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11004,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': Fatalfact1leftParent,
  'boss': 0,
  'level': 10,
  'battleCell': FF1LeftCell,
  'pos': Point3(3, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11005,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': Fatalfact1RightParent,
  'boss': 0,
  'level': 10,
  'battleCell': FF1RightCell,
  'pos': Point3(-3, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11006,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': Fatalfact1RightParent,
  'boss': 0,
  'level': 9,
  'battleCell': FF1RightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11007,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': Fatalfact1RightParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF1RightCell,
  'pos': Point3(3, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 11008,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(8, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(2, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(-4, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(-11, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(8, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(2, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(-4, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(-11, -7, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0}]
ReserveCogData = [{'type': 'm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 2,
  'battleCell': LobbyCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20009,
  'skeleton': 0,
  'joinParent': 20018},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 2,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': 0,
  'joinParent': 20019},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 2,
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': 0,
  'joinParent': 20019},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 3,
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 9,
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 2,
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20075,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 3,
  'battleCell': CenterSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 9,
  'battleCell': CenterSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 3,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 3,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 3,
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 3,
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 2,
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 2,
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 3,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': Fatalfact1leftParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF1LeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': Fatalfact1leftParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF1LeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': Fatalfact1RightParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF1RightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': Fatalfact1RightParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF1RightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 1},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact2BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF2BatRCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},
 {'type': 'mh',
  'parentEntId': FatalFact3BattleRoomParent,
  'boss': 0,
  'level': 12,
  'battleCell': FF3BatRCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0},]