from direct.distributed.MsgTypes import *
OTP_DO_ID_FRIEND_MANAGER = 4501
OTP_DO_ID_TOONTOWN = 1337
OTP_DO_ID_CLIENT_SERVICES_MANAGER = 4665
OTP_DO_ID_TTS_FRIENDS_MANAGER = 4666
OTP_DO_ID_GLOBAL_PARTY_MANAGER = 4477
OTP_DO_ID_GLOBAL_LOBBY_MANAGER = 4478
OTP_DO_ID_CHAT_MANAGER = 4681
OTP_ZONE_ID_MANAGEMENT = 2
OTP_ZONE_ID_DISTRICTS = 3
OTP_ZONE_ID_DISTRICTS_STATS = 4
OTP_MOD_CHANNEL = 6200
OTP_ADMIN_CHANNEL = 6400
OTP_SYSADMIN_CHANNEL = 6500
